### ISSUE TITLE
小伙子很有想法

### ISSUE THREAD

**Issue by Revincx** [skyil03/fxxkqndxx#1]
不过那个大学习是要后台查数据的，每过一段时间都会公示没弄的人。
所以光有截图可能是混不过去...

不过实测只用点进去视频再退出后台就会有数据，也不是那么麻烦嘛

---

我记得我高中的时候也这么干过，当初要的是完成页的截图，我就弄了个html放张图片上去截张图就交上去了，不过当时不咋管这个，没弄也不会催你咋的...

**Comment by crow0d** [comment]
当然知道点进去就有数据，不过最近让交学习记录的截图，所以有了这方面的想法。
基于懒人的体验，尝试给做成全自动的，最好可以截图、PS一键发到QQ是最好的了。~~可惜技术不行还在努力~~
~~以前尝试过python一键提交学习记录，但由于微信端Oauth2的授权登录，最终不了了之~~
<br>
其实还是我懒地截图P文字了....
